config/routes.rb
SampleApp::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]

   

  root to: 'static_pages#home'
  
  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  
  match '/signup', to: 'users#new'
  
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  

  match '/guidelines',    to: 'static_pages#guidelines'  
  match '/grid',    to: 'static_pages#grid'
  match '/font',    to: 'static_pages#font'

  match '/violator',    to: 'static_pages#violator' # explore violator
  match '/nav',    to: 'static_pages#nav'   # explore possible navigations
  match '/full',    to: 'static_pages#full' # prototype: overall page layout 
  match '/payroll',    to: 'static_pages#payroll'
  match '/dropdown',    to: 'static_pages#dropdown'
  
  
  match '/qb',    to: 'static_pages#qb'
  

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer         not null, primary key
#  name       :string(255)
#  email      :string(255)
#  created_at :datetime        not null
#  updated_at :datetime        not null
#

class User < ActiveRecord::Base
  attr_accessible :email, :name, :password, :password_confirmation
  has_secure_password
  
  before_save { |user| user.email = email.downcase }
  before_save :create_remember_token
  
  validates :name, presence: true, length: {maximum: 50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, 
                    format: { with: VALID_EMAIL_REGEX }, 
                    uniqueness: { case_sensitive: false }
          
  # validates :password, presence: true, length: { minimum: 6 }                  
  validates :password, length: { minimum: 6 }                  
  validates :password_confirmation, presence: true
  
  private

    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by_email(params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      # Sign the user in and redirect to the user's show page.
      sign_in user
      redirect_back_or user
    else
      # Create an error message and re-render the signin form.
      flash.now[:error] = 'Invalid email/password combination' # Not quite right!
      render 'new'
    end
  end
  
  def destroy
    sign_out
    redirect_to root_path
  end
  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
  def help
  end
  def about
  end
  def contact
  end
  # for gallery
  def guidelines
  end
  def grid
  end
  def font
  end
  def violator
  end
  def nav
    render :layout => "layouts/nav.html.erb"
  end
  def full
    render :layout => "layouts/full.html.erb"
  end
  def payroll
    render :layout => "layouts/payroll.html.erb"
  end
  def dropdown
    render :layout => "layouts/dropdown.html.erb"
  end
  def qb
    render :layout => "layouts/qb.html.erb"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :signed_in_user, only: [:index, :edit, :update]
  before_filter :correct_user, only: [:edit, :update]
  before_filter :admin_user,     only: :destroy
  
  def new
    @user = User.new
  end
  
  def index
    # @users = User.all
    @users = User.paginate(page: params[:page])
  end
  
  def show
    @user = User.find(params[:id])
  end
  
  def create
    @user = User.new(params[:user])
    if @user.save
      # Handle a successful save.
      sign_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end
  end
  
  def edit
    # @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      # Handle a successful update.
      flash[:success] = "Profile updated"
      sign_in @user
      redirect_to @user
    else
      render 'edit'
    end
  end
  
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User destroyed."
    redirect_to users_path
  end
  
  private

    def signed_in_user
      unless signed_in?
        store_location
        redirect_to signin_path, notice: "Please sign in."
      end
    end
    
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user)
    end
    def admin_user
      redirect_to(root_path) unless current_user.admin?
    end
    
      
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title)
    base_title = "Ruby on Rails Tutorial Sample App"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    cookies.permanent[:remember_token] = user.remember_token
    self.current_user = user
  end
  
  def current_user=(user)
    @current_user = user
  end
  
  def current_user
    @current_user ||= User.find_by_remember_token(cookies[:remember_token])
  end
  
  def current_user?(user)
    user == current_user
  end
  
  def signed_in?
    !current_user.nil?
  end
  
  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end
  
  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.fullpath
  end
      
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  # Returns the Gravatar (http://gravatar.com/) for the given user.
  # def gravatar_for(user)
  #   gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
  #   gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
  #   image_tag(gravatar_url, alt: user.name, class: "gravatar")
  # end
  
  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user, options = { size: 50 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <!-- <small>
    <a href="http://railstutorial.org/">Rails Tutorial</a>
    by Michael Hartl
  </small> -->
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<!-- <div class="navbar navbar-fixed-top"> -->
<div class="navbar">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Gallery", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <!-- <li><%= link_to "Home", root_path %></li> -->
          <li><%= link_to "Guidelines", guidelines_path %></li>
					<!-- <li><%= link_to "Help", help_path %></li> -->
          <li><%= link_to "Grid", grid_path %></li>
					<li><%= link_to "Font", font_path %></li>
					<li><%= link_to "Navigation", root_path %></li>
					<li><%= link_to "Templates", root_path %></li>
					<li><%= link_to "Examples", root_path %></li>

          <!-- <li><%= link_to "Help", help_path %></li>
          <% if signed_in? %>
            <li><%= link_to "Users", users_path %></li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %> -->
        </ul>
      </nav>
    </div>
  </div>
</div>
<div class="navbar dock hide">
	<div class="nav-wrapper">	
		<ul class="nav">
			<li><%= link_to "Payroll Services", root_path %></li>
			<li><%= link_to "Employee Benefits", root_path %></li>
			<li><%= link_to "Payroll 101", root_path %></li>
			<li><%= link_to "Hiring Employees", root_path %></li>
			<li><%= link_to "Support", root_path %></li>
			<li></li>
		</ul>
	</div>
	<div class="nav-wrapper">
		<ul class="nav">
			<li><%= link_to "Features", root_path %></li>
			<li><%= link_to "How it Works", root_path %></li>
			<li><%= link_to "Pricing", root_path %></li>
			<li><%= link_to "Reviews", root_path %></li>
			<li></li>
		</ul>		
	</div>

</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
	<link rel="stylesheet" href="http://f.fontdeck.com/s/css/QMzjnQmweVgbuFVAOrRDt3PxX9o/*.intuit.com/12758.css" type="text/css" /> 
	<!-- font for testing, only work for intuit.net  -->
	<link rel="stylesheet" href="http://f.fontdeck.com/s/css/QMzjnQmweVgbuFVAOrRDt3PxX9o/*.intuit.net/12758.css" type="text/css" /> 
</head>
<body>
	<%= render 'layouts/header' %>
    <div class="container">

	  <% flash.each do |key, value| %>
        <!-- <div class="alert alert-<%= key %>"><%= value %></div> -->
		 <%= content_tag(:div, value, class: "alert alert-#{key}") %>
      <% end %>

      <%= yield %>
  	  <%= render 'layouts/footer' %>
	  <%= debug(params) if Rails.env.development? %>
	</div>	
	

</body>
</html>

app/views/layouts/dropdown.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "payroll", :media => "all" %>
  <%= stylesheet_link_tag    "dropdown", :media => "all" %>
  <%= javascript_include_tag "dropdown" %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>

	<!-- 960 gridder http://peol.github.com/960gridder/ -->
	<script type="text/javascript">
	var gOverride = {
	  urlBase: 'http://gridder.andreehansson.se/releases/latest/',
	  gColor: '#EEEEEE',
	  gColumns: 12,
	  gOpacity: 0.35,
	  gWidth: 10,
	  pColor: '#C0C0C0',
	  pHeight: 6,
	  pOffset: 0,
	  pOpacity: 0.55,
	  center: true,
	  gEnabled: true,
	  pEnabled: true,
	  setupEnabled: true,
	  fixFlash: true,
	  size: 960
	};
	createGridder = function() {
	  document.body.appendChild(
	    document.createElement('script'))
	    .src='http://peol.github.com/960gridder/releases/1.3.1/960.gridder.js';
	}
</script>
</head>
<!-- <body onload="createGridder()"> -->
<body>
	
    <!-- <div class="container"> -->

    <%= yield %>
	  <!-- <%= debug(params) if Rails.env.development? %> -->
	<!-- </div>	 -->
</body>

</html>

app/views/layouts/full.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "full", :media => "all" %>
  <%= stylesheet_link_tag    "nav", :media => "all" %>
  <%= javascript_include_tag "full" %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
	<!-- <%= render 'layouts/nav_header' %> -->
    <!-- <div class="container"> -->

    <%= yield %>
	  <!-- <%= debug(params) if Rails.env.development? %> -->
	<!-- </div>	 -->
 <script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.5/jquery-ui.js"></script>
</body>

</html>

app/views/layouts/nav.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "nav", :media => "all" %>
  <!-- <%= stylesheet_link_tag    "nav-top", :media => "all" %> -->
  <!-- <%= javascript_include_tag "application" %> -->
  <%= javascript_include_tag "nav" %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
	<!-- <%= render 'layouts/nav_header' %> -->
    <div class="container">

      <%= yield %>
  	  <%= render 'layouts/footer' %>
	  <%= debug(params) if Rails.env.development? %>
	</div>	
 <script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.5/jquery-ui.js"></script>
</body>

</html>

app/views/layouts/payroll.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "payroll", :media => "all" %>
  <%= javascript_include_tag "payroll" %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>

	<!-- 960 gridder http://peol.github.com/960gridder/ -->
	<script type="text/javascript">
	var gOverride = {
	  urlBase: 'http://gridder.andreehansson.se/releases/latest/',
	  gColor: '#EEEEEE',
	  gColumns: 12,
	  gOpacity: 0.35,
	  gWidth: 10,
	  pColor: '#C0C0C0',
	  pHeight: 6,
	  pOffset: 0,
	  pOpacity: 0.55,
	  center: true,
	  gEnabled: true,
	  pEnabled: true,
	  setupEnabled: true,
	  fixFlash: true,
	  size: 960
	};
	createGridder = function() {
	  document.body.appendChild(
	    document.createElement('script'))
	    .src='http://peol.github.com/960gridder/releases/1.3.1/960.gridder.js';
	}
</script>
</head>
<!-- <body onload="createGridder()"> -->
<body>
	
    <!-- <div class="container"> -->

    <%= yield %>
	  <!-- <%= debug(params) if Rails.env.development? %> -->
	<!-- </div>	 -->
</body>

</html>

app/views/layouts/qb.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "reset", :media => "all" %>
  <%= stylesheet_link_tag    "style", :media => "all" %>
  <%= stylesheet_link_tag    "qb", :media => "all" %>
  <%= javascript_include_tag "qb" %>
  <%= javascript_include_tag "do" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render 'layouts/qb/header' %>
   <div class="container">
    <%= yield %>

	  <!-- <%= debug(params) if Rails.env.development? %> -->
	</div>	
  <%= render 'layouts/qb/footer' %>
</body>

</html>

app/views/layouts/qb/_header.html.erb
<div id="quickNav" class="quickNav-header property-header quickbooks">
	
	<div id="moreFromIntuit" class="more-from-intuit">
		<div class="more-from-intuit-container">

			<form role="search" action="//www.intuit.com/sbweb/common/catalog/category/internal_search/search_redirect.jsp" method="get">
				<label for="searchIntuit" class="visually-hidden">Search Intuit Small Business</label>
				<input id="searchIntuit" name="searchIntuit" type="text" class="search-intuit" placeholder="Search Intuit">
                </form>

		</div>
	</div>

	<div class="top-bar">
		<div class="top-bar-container">
			
			<a class="intuit-logo visually-hidden-text" href="http://quickbooks.intuit.com">
				Intuit: Small business, rejoice.&#8482;
				<span class="intuit-logo-image">Intuit Logo</span>
				<span class="property-logo-image">Quickbooks Logo</span>
			</a>
			
			<ul class="quickNav-menu nav-links">
				<li>
					<div class="phone-number">(877) 683-3280</div>
				</li>
				<li>
					<a href="#Security">Security</a>
				</li>
				<li>
					<a href="#My Cart">My Cart (<span id="cartItemCount" class="cart-item-count">0</span>)</a>
				</li>
				<li class="sub-menu">
					<a href="#Sign In">Sign In<span class="sub-menu-icon"></span></a>
					<ul>
						<li><a href="#Intuit Websites">Intuit Websites</a></li>
						<li><a href="#QuickBooks Online">QuickBooks Online</a></li>
						<li><a href="#Intuit Payroll">Intuit Payroll</a></li>
						<li><a href="#Other Services">Other Services</a></li>
					</ul>
				</li>
				<li>
					<a href="#More From Intuit" id="moreFromIntuitLink" class="more-from-intuit-link">More From Intuit<span class="more-from-intuit-link-icon"></span></a>						
				</li>
			</ul>

		</div>
	</div>
	
	<div class="nav-bar">
		<div class="nav-bar-container">

			<ul class="quickNav-menu phone-info">
				<li class="sub-menu">
					<div>
						<span class="phone-icon"></span><span class="phone-number">(877) 683-3280</span><span class="info-icon"></span>
					</div>
					<ul>
						<li>
							<div class="call-center-status">SALES: Currently <span class="open">Open!</span><span class="closed">Closed</span></div>
							Mon. - Fri. 5 AM - 6 PM PT
						</li>
						<li class="more-phone-numbers">
							<a href="//about.intuit.com/contact/">More phone numbers&hellip;</a>
						</li>
					</ul>
				</li>
			</ul>

			<ul class="quickNav-menu">					
				<li class="sub-menu">
					<a href="#Bookkeeping and Accounting Software">Bookkeeping and Accounting Software</a>
					<ul>
						<li>
							<a href="#Online Accounting Software">Online Accounting Software</a>
						</li>
						<li>
							<a href="#Bookkeeping">Bookkeeping</a>
						</li>
					</ul>
				</li>
				<li class="sub-menu">
					<a href="#Business Software">Business Software</a>
					<ul>
						<li>
							<a href="#Contractor and Construction Accounting">Contractor and Construction Accounting</a>
						</li>
						<li>
							<a href="#Manufacturing">Manufacturing</a>
						</li>
						<li>
							<a href="#Nonprofit Accounting">Nonprofit Accounting</a>
						</li>
						<li>
							<a href="#Professional Services">Professional Services</a>
						</li>
						<li>
							<a href="#Retail Accounting">Retail Accounting</a>
						</li>
						<li>
							<a href="#Enterprise Accounting">Enterprise Accounting</a>
						</li>
						<li>
							<a href="#Accountants">Accountants</a>
						</li>
					</ul>
				</li>
				<li>
					<a href="#Checks and Supplies">Checks and Supplies</a>
				</li>					
				<li class="sub-menu">
					<a href="#Support">Support</a>
					<ul>
						<li>
							<a href="#QuickBooks Support">QuickBooks Support</a>
						</li>
						<li>
							<a href="#QuickBooks Online Support">QuickBooks Online Support</a>
						</li>
						<li>
							<a href="#QuickBooks User Community">QuickBooks User Community</a>
						</li>
						<li>
							<a href="#QuickBooks Support Plans">QuickBooks Support Plans</a>
						</li>
					</ul>
				</li>
			</ul>
		</div>
	</div>
</div>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<h1>About Us</h1>
<p>
  The <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
  is a project to make a book and screencasts to teach web development
  with <a href="http://rubyonrails.org/">Ruby on Rails</a>. This
  is the sample application for the tutorial.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  Contact Ruby on Rails Tutorial about the sample app at the
  <a href="http://railstutorial.org/contact">contact page</a>.
</p>

app/views/static_pages/dropdown.html.erb
<header>
	<div class="top-border"></div>
	<div class="container"><%= link_to "", root_path, id: "ilogo" %></div>
	<section class="main-nav">
		<div class="container">		
			<div class="main-nav-li">
				<ul>
					<li><a href="#">Quickbooks</a></li>
					<li><a href="#">Payroll Services</a></li>
					<li><a href="#">Merchant Services</a></li>
					<li><a href="#">Checks & Supplies</a></li>
					<li><a href="#">Support</a></li>
				</ul>
			</div>
		</div>
	</section>
</header>
<section id="hero">
	<div id="hero-inner"></div>
</section>
<section id="pnav-holder">
	<section id="pnav-wrapper" class="pnav-container">
		<section id="pnav-top">
			<section class="container">
				<div class='row'>	
					<div class='span5 pnav1c'>		
						<h3>Intuit Online Payroll Plus</h3>
						<p>Free trial. No credit card required.</p>
					</div>

					<div class="span4 offset2 dropdown1">
						<!-- <div class="dropdown">
						  <a class="dropdown-toggle" href="#">Dropdown</a>
						  <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
								 <li>Unlimited</li>
								 <li>Pro</li>
						  </ul>
						</div> -->
						<div class="option pull-left">	
							<div class='arrow-down'></div>					
							<select class="">
							  <option>Unlimited</option>
							  <option>Pro</option>
							  <option>Basic</option>
							</select> 

						</div>
						<button class='btn1 pull-left'>Buy Now</button>
					</div>
				</div>
			</section>
		</section>
		<section id="pnav">
			<div class="navba">
					<ul class="navh container">
						<li><a href="#overview">Overview</a></li>
						<li><a href="#features">Features</a></li>
						<li><a href="#how">How it Works</a></li>
						<li><a href="#pricing">Pricing</a></li>
						<li><a href="#reviews">Customer Reviews</a></li>
					</ul>					
			</div>

		</section>
		<div class='arrow-shadow'>	
			<div class="arrow-ld pull-left"></div>
			<div class="arrow-rd pull-right"></div>
		</div>
	</section>
</section>

<div class="outer-container">
	<section id="overview" class="sec container">
		<h2>Overview</h2>
		<p class="b">Intuit Online Payroll makes it easy to run payroll anytime, anywhere in 3 easy steps.</p>
		<div class="row">
			<div class="span8">
				<div class="join-biz"></div>
			</div>
			<div class="span3">
				<div class="join-biz-video"></div>
			</div>
		</div>
	</section>
	<div class="full-h-divider"></div>
	<section id="features" class="sec container">
		<h2>Features</h2>
	</section>
	<section id="how" class="sec container">
		<h2>How it Works</h2>
	</section>
	<section id="pricing" class="sec container">
		<h2>Pricing</h2>
	</section>
	<section id="reviews" class="sec container">
		<h2>Our Customer Stories</h2>
	</section>
</div>

app/views/static_pages/guidelines.html.erb
<header class="jumbotron subhead" id="overview">
  <h1>Guidelines</h1>
	<p class="leading">Global guidlines</p>
</header>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<p>
  Get help on the Ruby on Rails Tutorial at the
  <a href="http://railstutorial.org/help">Rails Tutorial help page</a>.
  To get help on this sample app, see the
  <a href="http://railstutorial.org/book">Rails Tutorial book</a>.
</p>

app/views/static_pages/home.html.erb
<!-- <div class="center hero-unit"> -->
<div class="jumbotron masthead">
  <h1>Templates Gallery Powered by <%= link_to image_tag("rails.png", alt: "Rails"), 'http://rubyonrails.org/' %></h1>

  <!-- <h2>
    This is the home page for the
    <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
    sample application.
  </h2>
	
  <%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary" %> -->
</div>

app/views/static_pages/nav.html.erb
<!-- <div class="navbar navbar-fixed-top"> -->
<section class="navbar">
   <%= link_to "", root_path, id: "ilogo" %>
				
  <div class="navbar-inner" id="navbar1">
    <div class="container">
      <!-- <nav> -->
        <ul class="nav">
					<li><%= link_to "Payroll Services", root_path %></li>
					<li><%= link_to "Employee Benefits", root_path %></li>
					<li><%= link_to "Payroll 101", root_path %></li>
					<li><%= link_to "Hiring Employees", root_path %></li>
					<li><%= link_to "Support", root_path %></li>
        </ul>
      <!-- </nav> -->
    </div>
  </div>
</section>
<div class="navbar hide" id="dock">
	<div class="container">	
		<div class="nav-wrapper" id="navbar2">	
			<ul class="nav">
				<li><%= link_to "Payroll Services", root_path %></li>
				<li><%= link_to "Employee Benefits", root_path %></li>
				<li><%= link_to "Payroll 101", root_path %></li>
				<li><%= link_to "Hiring Employees", root_path %></li>
				<li><%= link_to "Support", root_path %></li>
			</ul>
		</div>
		<div class="nav-wrapper" id="navbar3">
			<ul class="nav">
				<li><%= link_to "Features", "#features" %></li>
				<li><%= link_to "How it Works", "#works" %></li>
				<li><%= link_to "Pricing", "#pricing" %></li>
				<li><%= link_to "Reviews", "#reviews" %></li>
				<li></li>
			</ul>		
		</div>
		<img class="center" src="/assets/arrow-up.png" alt="" />
	</div>
</div>
<div class="nav-container">
	<div id="hero">
		<h1>Hero</h1>
	</div>
	<div id="navbar4">
		<div class="container">		
			<ul class="nav">
				<li id="nav-features"><%= link_to "Features", "#features" %></li>
				<li id="nav-works"><%= link_to "How it Works", "#works" %></li>
				<li id="nav-pricing"><%= link_to "Pricing", "#pricing" %></li>
				<li id="nav-reviews"><%= link_to "Reviews", "#reviews" %></li>
			</ul>		
		</div>
	</div>
	<section id="features">
		<h1>Features</h1>
	</section>
	<section id="works">
		<h1>How it Works</h1>
	</section>
	<section id="pricing">
		<h1>Pricing</h1>
	</section>
	<section id="reviews">
		<h1>Reviews</h1>
	</section>
</div>

app/views/static_pages/violator.html.erb
<div id="violator">
	<div id="banner"></div>
</div>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 52 %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
  <% end %>
</li>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="span4">
    <section>
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>